name: "Build"

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Python 3.11"
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: "Build"
        run: |
          python -m pip install -U pip
          python -m pip install -Ur requirements.txt
          python -m build
          ls -lAh

      - name: "Upload to Actions"
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: dist/

      - name: "Upload to Release"
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
